// Code generated by coattail; DO NOT EDIT.
package internal

import (
    "context"

	"github.com/nathan-fiscaletti/coattail-go/pkg/coattailtypes"
)

func RegisterUnits(ctx context.Context, local *coattailtypes.Peer) error {
    return nil
}
