name: coattail-demo

services:
  auth-service:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOOS=linux
      - GOARCH=amd64
    ports:
      - "5244:5243"
      - "8084:8082"
      - "8085:8083"
    working_dir: /app/demo/auth-service
    command: ["./auth-service"]
    networks:
      coattail-demo:
        ipv4_address: 192.168.100.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOOS=linux
      - GOARCH=amd64
    ports:
      - "5245:5243"
      - "8086:8082"
      - "8087:8083"
    working_dir: /app/demo
    entrypoint: ["sh", "-c", "go run .scripts/generate-web-peers.go && cd web-service && exec ./web-service"]
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      coattail-demo:
        ipv4_address: 192.168.100.3

networks:
  coattail-demo:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24