version: "3"

includes:
  demo: demo/demo.yaml

tasks:
  run:
    desc: Run the local peer
    cmd: go run ./cmd
    dir: demo/ct1
  
  run-remote:
    desc: Run the remote peer
    cmd: go run ./cmd
    dir: demo/ct2