version: "3"

tasks:
  run:
    desc: Run the local peer
    cmd: go run ../cmd/peer-1
    dir: demo
  
  run-remote:
    desc: Run the remote peer
    cmd: go run ../cmd/peer-2
    dir: demo