// Code generated by coattail; DO NOT EDIT.
package internal

import (
    "coattail_app/internal/actions"
    
	"coattail_app/pkg/types"
	"context"

	"github.com/nathan-fiscaletti/coattail-go/pkg/coattailtypes"
)

func RegisterUnits(ctx context.Context, local *coattailtypes.Peer) error {
    var err error

    // Register actions
    
    err = local.RegisterAction(ctx, "Authenticate", coattailtypes.NewAction[types.Request , types.Response](&actions.Authenticate{}))
    if err != nil {
        return err
    }
    
    // Register receivers
    
    return nil
}
