service:
  log_packets: false
  address:
    host: 0.0.0.0
    port: 5243

api:
  enabled: true
  address:
    host: 0.0.0.0
    port: 8082

web:
  enabled: false
  address:
    host: 0.0.0.0
    port: 8083